version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      is_debug: ${is_debug}
      admin_id: ${admin_id}
      bot_token: ${bot_token}
      server_address: ${server_address}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/nginx/certs

    depends_on:
      - app